OFLAG= -I/usr/local/include -L/usr/local/lib -lcfitsio -lm  -Wall
OFLAGS = -lm -Wall

bpcorrect: bpcorrect.c
	gcc -g -o bpcorrect bpcorrect.c $(OFLAG)

getcenterpos: getcenterpos.c
	gcc -g -o getcenterpos getcenterpos.c $(OFLAG)

#imcentre: imcentre.c
#	gcc -g -o imcentre imcentre.c $(OFLAGS)
